export const TOGGLE_LOGIN = 'TOGGLE_LOGIN';
export const SET_LOGIN = 'SET_LOGIN';
export const LOGOUT = 'LOGOUT';
export const ACTIVATE_REQUEST = 'ACTIVATE_REQUEST';
export const ACTIVATE_SUCCESS = 'ACTIVATE_SUCCESS';
export const ACTIVATE_FAIL = 'ACTIVATE_FAIL';
export const ACTIVATE_CLOSE = 'ACTIVATE_CLOSE';
export const TOGGLE_SINGUP = 'TOGGLE_SINGUP';
export const SIGNUP_SUCCEED_OPEN = 'SIGNUP_SUCCEED_OPEN';
export const SIGNUP_SUCCEED_CLOSE = 'SIGNUP_SUCCEED_CLOSE';

